#!/bin/zsh

function valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

function ros_setup_usage() {
    echo "Usage:  ros_setup [-v][-a][-h][-p] <n>"
    echo " -v Use VPN IP address instead of name (10.210.232.103 instead of bar3)"
    echo " -a Use AWS VPN IP address instead of name (172.210.220.103 instead of bar3)"
    echo " -p Setup a route to the payload shuttle"
    echo " -h Display this help message"
    echo " n = bar<n> or IP address"
    echo " Examples:"
    echo " ros_setup 3"
    echo "     ROS_MASTER=http://bar3:11311"
    echo "     ROS_HOSTNAME=$(hostname)"
    echo " ros_setup -v 3"
    echo "     ROS_MASTER=http://10.210.232.103:11311"
    echo "     ROS_HOSTNAME=$(hostname -I)"
    echo " ros_setup -a 3"
    echo "     ROS_MASTER=http://172.210.220.103:11311"
    echo "     ROS_HOSTNAME=$(hostname -I)"
    echo " ros_setup 10.10.39.209"
    echo "     ROS_MASTER=http://10.10.39.209:11311"
    echo "     ROS_HOSTNAME=$(hostname -I)"
    echo " "
    return 1
}

vpn=0
avpn=0
payload=0
while getopts ":vahp" opt "$@"; do
  case $opt in
    v)
        vpn=1
        shift $((OPTIND-1))
      ;;
    a)
        avpn=1
        shift $((OPTIND-1))
      ;;
    p)
        payload=1
        shift $((OPTIND-1))
      ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        ros_setup_usage
      ;;
    h)
      ros_setup_usage
      ;;
  esac
done

if [ -z "$1" ] ; then
    ros_setup_usage
    return 1
fi

bnum="${@: -1}"
hname=$(hostname)
if valid_ip ${@: -1}; then
    bnum="${@: -1}"
    hname=$(hostname -I)
elif [[ ${bnum} =~ ^[0-9]+$ ]]; then
    hostI=$(hostname -I)
    if [ $vpn -eq 1 ] ; then
        bnum=10.210.232.$((100+$bnum))
        for addr in ${(z)hostI}; do
            [[ $addr =~ "10.220" ]] && hname=$addr
        done
    elif [ $avpn -eq 1 ] ; then
        bnum=172.21.220.$((100+$bnum))
        for addr in ${(z)hostI}; do
            [[ $addr =~ "172.21" ]] && hname=$addr
        done
    else ipnum=${bnum}
         bnum=bar${bnum}
         hname=$(hostname)
    fi
fi

export ROS_MASTER_URI=http://$bnum:11311
echo "ROS_MASTER_URI=$ROS_MASTER_URI"
export ROS_HOSTNAME=$hname
echo "ROS_HOSTNAME=$ROS_HOSTNAME"

if [ $payload -eq 1 ] ; then
    echo sudo route add -net 10.110.1.0/24 gw $bnum
    sudo route add -net 10.110.1.0/24 gw $bnum
    echo sudo route add -net 10.110.$ipnum.0/24 gw $bnum
    sudo route add -net 10.110.$ipnum.0/24 gw $bnum
fi
