#!/bin/bash

echo export ROS_MASTER_URI=http://bar$1:11311
export ROS_MASTER_URI=http://bar$1:11311
echo export ROS_HOSTNAME=$(hostname)
export ROS_HOSTNAME=$(hostname)

echo "Do you want to set the route to the payload?"
read response
if [[ $response == [yY] ]] ; then
    echo sudo route add -net 10.110.$1.0/24 gw 10.210.232.$((100+$1))
    sudo route add -net 10.110.$1.0/24 gw 10.210.232.$((100+$1))
fi
