#!/bin/bash
# Wrapper script to ssh to a robot. It starts a private instance of ssh-agent
# that makes the user's github key (and only that key) available during the
# session. It also environment variables for the user's git identity, read
# from the local machine's ~/.gituser file.

function valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

function usage() {
    echo "Usage:  sshbar [-d <path>] [-s | -k] [-p] [-h] <n>"
    echo ""
    echo "Options:"
    echo " -h Display this help message"
    echo " -d Use <path> for keys *see notes*"
    echo " -s Use barkey for authentication (core; port 2222)"
    echo " -k Use barkey for authentication (classic; port 22)"
    echo " -p login to payload instead of truck (port 3022 or 3222)"
    echo " n = bar<n> or IP address"
    echo ""
    echo " Examples:"
    echo " sshbar 672"
    echo "     ssh bar@bar672"
    echo " sshbar -p 672"
    echo "     ssh -i /.ssh/id_rsa-<hostname>-github -p3022 bar@bar672"
    echo " sshbar -ps 672"
    echo "     ssh -i /data/.secrets/barkey -p3222 bar@bar672"
    echo " sshbar -s 672"
    echo "     ssh -i /data/.secrets/barkey -p2222 bar@bar672"
    echo " sshbar -k 672"
    echo "     ssh -i /data/.secrets/barkey -p22 bar@bar672"
    echo " sshbar -kd /home/dnorris/.secrets 672"
    echo "     ssh -i /home/dnorris/.secrets/barkey -p22 bar@bar672"
    echo " sshbar 10.10.39.209"
    echo "     ssh bar@10.10.39.209"
    echo ""
    echo "NOTE: 1. -s and -k options use the barkey for authentication."
    echo "         when not specified, authentication uses"
    echo "         id_rsa-<hostname>-github"
    echo "      2. The defalt path is ~/.ssh when -s or -k are not specified."
    echo "         If -s or -k are specified, the default path is /data/.secrets"
    echo "      3. The env var SECRET_PATH will override the default for both cases."
    exit 1
}


prod=0
payload=0
secret=0
dev=0
user_path=0
if [ -z $SECRET_PATH ] ; then
    secret_path=$HOME/.ssh
else
    secret_path=$SECRET_PATH
fi

while getopts ":hpskd:" opt; do
  case $opt in
    d)
        user_path=1
        secret_path=$OPTARG
        shift $((OPTIND-1))
      ;;
    p)
        payload=1
        shift $((OPTIND-1))
      ;;
    s)
        if [ $dev -eq 1 ] ; then
            usage
        fi
        prod=1
        secret=1
        if [ $user_path -ne 1 ] ; then
          if [ -z $SECRET_PATH ] ; then
              secret_path='/data/.secrets'
          else
              secret_path=$SECRET_PATH
          fi
        fi
        shift $((OPTIND-1))
      ;;
    k)
        if [ $prod -eq 1 ] ; then
            usage
        fi
        dev=1
        secret=1
        if [ $user_path -ne 1 ] ; then
          if [ -z $SECRET_PATH ] ; then
              secret_path='/data/.secrets'
          else
              secret_path=$SECRET_PATH
          fi
        fi
        shift $((OPTIND-1))
      ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        usage
      ;;
    h)
      usage
      ;;
  esac
done

if [ -z "$1" ] ; then
    usage
fi

host="${@: -1}"
if valid_ip ${@: -1}; then
    host="${@: -1}"
elif [[ ${host} =~ ^[0-9]+$ ]]; then
    host=bar${host};
fi

if [ $secret -eq 1 ] || [ $dev -eq 1 ] ; then
    id_file=${secret_path}/barkey
else
    if [[ -e ${secret_path}/id_ed25519-$(hostname)-github ]] ; then
        id_file=${secret_path}/id_ed25519-$(hostname)-github
    elif [[ -e ${secret_path}/id_rsa-$(hostname)-github ]] ; then
        id_file=${secret_path}/id_rsa-$(hostname)-github
    else
        echo 'Identity File not found'
        exit 1
    fi
fi

zshell=0
xfor=0
if [ $prod -eq 1 ] ; then
    if [ $payload -eq 1 ] ; then
        port='3222'
    else
        port='2222'
    fi
elif [ $payload -eq 1 ] ; then
    port='3022'
    zshell=1
    xfor=1
else
    port='22'
    zshell=1
    xfor=1
fi

if [ $zshell -eq 1 ] ; then
    shell='zsh'
else
    shell='bash'
fi

if [ $xfor -eq 1 ] ; then
    options='-X -t -A'
else
    options='-t -A'
fi

uds_addr=$(mktemp --dry-run $XDG_RUNTIME_DIR/ssh-agent-XXXXXX)
git_email=$(sed -n -e 's/^\s\+email\s\?=\s\?//p' < ~/.gituser)
git_name=$(sed -n -e 's/^\s\+name\s\?=\s\?//p' < ~/.gituser | sed -e 's/\s/\\ /')

exec ssh-agent -a $uds_addr ssh ${options} -p${port} -l bar \
    -o IdentityFile=$id_file -o AddKeysToAgent=yes -l bar ${host} \
    GIT_AUTHOR_EMAIL="${git_email}" \
    GIT_COMMITTER_EMAIL="${git_email}" \
    GIT_AUTHOR_NAME="${git_name}" \
    GIT_COMMITTER_NAME="${git_name}" \
    EDITOR=emacs \
    TERM=screen-256color \
    ${shell} ;
