#!/bin/bash

function usage() {
    echo "Usage:  start-badger-vpn [-i[timeout]]"
    echo " -h Display this help message"
    echo " -i inactive timeout default=300 sec"
    exit 1
}

inactive=300

while getopts ":hi:" opt; do
  case $opt in
    i)
        inactive=$OPTARG
        shift $((OPTIND-1))
      ;;
    \?)
        echo "Invalid option: -$OPTARG" >&2
        usage
      ;;
    h)
      usage
      ;;
  esac
done

sudo openvpn --config ~/badger-vpn/duane.ovpn --auth-user-pass ~/badger-vpn/badger.up --inactive $inactive 20000
